name: GenerateBoard

# Controls when the action will run.
on:
  # Triggers the workflow on push of repository
  push:
    branches: [ main ]
  # Can add a schedule cron of when to run action but leaving this commented out for now
  schedule:
   - cron: '0 23 * * 5'
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # PHP GitHub Action created by https://github.com/nanasess
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '8.3'
    # This triggers our php file we created before
    - name: Run PHP
      run: php ./generateBoard.php
    - name: Commit Changes
      run:
        git config --local user.name actions-user

        git config --local user.email "giantpaper@outlook.com"

        git fetch

        git add *

        git commit -am "GH Action   ./ready/* Updated    $(date)"

        git push -f origin main
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
